language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php CreatePhar.php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 7.4snapshot

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "revive.phar"
  skip_cleanup: true
  on:
    php: 7.3
#    tags: true
