language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

before_script:
  - travis_retry composer self-update
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - composer install ${COMPOSER_FLAGS} --no-interaction --no-dev
  - php CreatePhar.php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 7.4snapshot

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "revive.phar"
  skip_cleanup: true
  on:
    all_branches: true
#    tags: true
    php: 7.3
